package com.rt.springboot.app.e2e;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.test.context.ActiveProfiles;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertTrue;

@ActiveProfiles("test")
public class CreateInvoiceTest extends E2ETestBase {

    @Test
    public void shouldCreateInvoiceForExistingClient() throws InterruptedException {
        // Log in first
        driver.get(baseUrl() + "/login");
        driver.findElement(By.id("username")).sendKeys("admin");
        driver.findElement(By.id("password")).sendKeys("12345");
        driver.findElement(By.cssSelector("button[type=submit]")).click();

        // Wait for list page
        new WebDriverWait(driver, Duration.ofSeconds(5))
                .until(d -> d.getPageSource().contains("Listado de Clientes") || d.getPageSource().contains("Customer List"));

        // Pick first client's create-invoice button (if present)
        // The list template renders invoice creation links with href like /invoice/form/{clientId}
        WebElement invoiceBtn = driver.findElement(By.cssSelector("a[href^='/invoice/form/']"));
        invoiceBtn.click();

        // Wait for invoice form
        new WebDriverWait(driver, Duration.ofSeconds(5))
                .until(ExpectedConditions.presenceOfElementLocated(By.name("description")));

        // Fill minimal invoice data
        driver.findElement(By.name("description")).sendKeys("E2E Invoice");
        driver.findElement(By.name("observation")).sendKeys("Generated by e2e test");
        driver.findElement(By.name("search_product")).sendKeys("Apple iPod");
        // Wait for autocomplete options to appear
        new WebDriverWait(driver, Duration.ofSeconds(5))
                .until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("#ui-id-1 > li > div")));
        // Select item
        driver.findElement(By.cssSelector("#ui-id-1 > li > div")).click();

        driver.findElement(By.cssSelector("form[action='/invoice/form'] input[type=submit]")).click();

        // Wait for invoice details page with the new invoice
        new WebDriverWait(driver, Duration.ofSeconds(5))
                .until(d -> d.getPageSource().contains("E2E Invoice"));

        assertTrue(driver.getPageSource().contains("E2E Invoice"));
    }
}
